### ISSUE TITLE
scripts don't work.

### ISSUE THREAD

**Issue by fairy-of-9** [mandarjoshi90/coref#1]
### issue#1
**command** : ./download_pretrained.sh bert-base
**error** : HTTP request sent, awaiting response... 404 Not Found

-------------
### issue#2
**command** : GPU=0 python train.py best
**error** :
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    model = util.get_model(config)
  File "/data/BERT-coref/coref/util.py", line 21, in get_model
    return independent.CorefModel(config)
  File "/data/BERT-coref/coref/independent.py", line 32, in __init__
    self.bert_config = modeling.BertConfig.from_json_file(config["bert_config_file"])
  File "/home/fairy_of_9/anaconda3/envs/bert/lib/python3.6/site-packages/pyhocon/config_tree.py", line 366, in __getitem__
    val = self.get(item)
  File "/home/fairy_of_9/anaconda3/envs/bert/lib/python3.6/site-packages/pyhocon/config_tree.py", line 209, in get
    return self._get(ConfigTree.parse_key(key), 0, default)
  File "/home/fairy_of_9/anaconda3/envs/bert/lib/python3.6/site-packages/pyhocon/config_tree.py", line 151, in _get
    raise ConfigMissingException(u"No configuration setting found for key {key}".format(key='.'.join(key_path[:key_index + 1])))
pyhocon.exceptions.ConfigMissingException: 'No configuration setting found for key bert_config_file'

-------------
### experiments.conf
```
best {
  # Edit this
  data_dir = data_set
  model_type = independent
  # Computation limits.
  max_top_antecedents = 50
  max_training_sentences = 5
  top_span_ratio = 0.4
  max_num_speakers = 20
  max_segment_len = 64 #256

  # Learning
  bert_learning_rate = 1e-5
  task_learning_rate = 2e-4
  num_docs = 2802

  # Model hyperparameters.
  dropout_rate = 0.3
  ffnn_size = 500 #1000
  ffnn_depth = 1
  num_epochs = 20
  feature_size = 20
  max_span_width = 30
  use_metadata = true
  use_features = true
  use_segment_distance = true
  model_heads = false #true
  coref_depth = 2
  coarse_to_fine = true
  fine_grained = true
  use_prior = true

  # Other.
  train_path = data_set/train.english.jsonlines
  eval_path = data_set/dev.english.jsonlines
  conll_eval_path = data_set/dev.english.v4_gold_conll
  single_example = true
  genres = ["bc", "bn", "mz", "nw", "pt", "tc", "wb"]
  eval_frequency = 1000
  report_frequency = 100
  log_root = logs
  adam_eps = 1e-6
  task_optimizer = adam
}

bert_base = ${best}{
  num_docs = 2802
  bert_learning_rate = 1e-05
  task_learning_rate = 0.0002
  max_segment_len = 128
  ffnn_size = 3000
  train_path = data_set/train.english.128.jsonlines
  eval_path = data_set/dev.english.128.jsonlines
  conll_eval_path = data_set/dev.english.v4_gold_conll
  max_training_sentences = 11
  bert_config_file = ${best.log_root}/bert_base/bert_config.json
  vocab_file = ${best.log_root}/bert_base/vocab.txt
  tf_checkpoint = ${best.log_root}/bert_base/model.max.ckpt
  init_checkpoint = ${best.log_root}/bert_base/model.max.ckpt
}
...
```

------------

Is there anything I missed?

**Comment by fairy-of-9** [comment]
`./download_pretrained.sh` is work!


but.. I did run 
`./download_pretrained.sh bert_base`  (data_dir=logs)
so It's my directory
![image](https://user-images.githubusercontent.com/37280914/63827979-f17d1400-c99f-11e9-9823-dac035a8469c.png)

and my experiments.conf
```
data_dir=data

best {
  # Edit this
  data_dir = data
  model_type = independent
  # Computation limits.
  max_top_antecedents = 50
  max_training_sentences = 5
  top_span_ratio = 0.4
  max_num_speakers = 20
  max_segment_len = 256

  # Learning
  bert_learning_rate = 1e-5
  task_learning_rate = 2e-4
  num_docs = 2802

  # Model hyperparameters.
  dropout_rate = 0.3
  ffnn_size = 1000
  ffnn_depth = 1
  num_epochs = 20
  feature_size = 20
  max_span_width = 30
  use_metadata = true
  use_features = true
  use_segment_distance = true
  model_heads = true
  #model_heads = false
  coref_depth = 2
  coarse_to_fine = true
  fine_grained = true
  use_prior = true

  # Other.
  train_path = train.english.jsonlines
  eval_path = dev.english.jsonlines
  conll_eval_path = dev.english.v4_gold_conll
  single_example = true
  genres = ["bc", "bn", "mz", "nw", "pt", "tc", "wb"]
  eval_frequency = 1000
  report_frequency = 100
  #log_root = ${data_dir}
  log_root = logs
  adam_eps = 1e-6
  task_optimizer = adam
}

bert_base = ${best}{
  num_docs = 2802
  bert_learning_rate = 1e-05
  task_learning_rate = 0.0002
  max_segment_len = 128
  ffnn_size = 3000
  train_path = ${data_dir}/train.english.128.jsonlines
  eval_path = ${data_dir}/dev.english.128.jsonlines
  conll_eval_path = ${data_dir}/dev.english.v4_gold_conll
  max_training_sentences = 11
  bert_config_file = ${best.log_root}/bert_base/bert_config.json
  vocab_file = ${best.log_root}/bert_base/vocab.txt
  tf_checkpoint = ${best.log_root}/bert_base/model.max.ckpt
  init_checkpoint = ${best.log_root}/bert_base/model.max.ckpt
}


```
and used **command : GPU=0 python evaluate.py bert_base**


**result**
```
Use standard file APIs to check for files with this prefix.
Loaded 0 eval examples.
Predicted conll file: /tmp/tmpi6yrp0jo
Official result for muc
version: 8.01 /data/BERT-coref/coref/conll-2012/scorer/v8.01/lib/CorScorer.pm

====== TOTALS =======
Identification of Mentions: Recall: (0 / 0) 0%  Precision: (0 / 0) 0%   F1: 0%
--------------------------------------------------------------------------
Coreference: Recall: (0 / 0) 0% Precision: (0 / 0) 0%   F1: 0%
--------------------------------------------------------------------------

Official result for bcub
version: 8.01 /data/BERT-coref/coref/conll-2012/scorer/v8.01/lib/CorScorer.pm

====== TOTALS =======
Identification of Mentions: Recall: (0 / 0) 0%  Precision: (0 / 0) 0%   F1: 0%
--------------------------------------------------------------------------
Coreference: Recall: (0 / 0) 0% Precision: (0 / 0) 0%   F1: 0%
--------------------------------------------------------------------------

Official result for ceafe
version: 8.01 /data/BERT-coref/coref/conll-2012/scorer/v8.01/lib/CorScorer.pm

====== TOTALS =======
Identification of Mentions: Recall: (0 / 0) 0%  Precision: (0 / 0) 0%   F1: 0%
--------------------------------------------------------------------------
Coreference: Recall: (0 / 0) 0% Precision: (0 / 0) 0%   F1: 0%
--------------------------------------------------------------------------

Average F1 (conll): 0.00%
Average F1 (py): 0.00% on 0 docs
Average precision (py): 0.00%
Average recall (py): 0.00%

```

I think, eval examples not loaded.

**Comment by fairy-of-9** [comment]
I edited my comment.
Could you read it again?

**Comment by fairy-of-9** [comment]
Oh.. every conll, jsonlines files are empty. 
Sorry. Thanks your comments.

**Comment by henlein** [comment]
Thank you for publishing the code.
Is the correct general input format for predict.py like the above input or like in the readme?
You also need the jsonkey: sentence_map.
How is this input structured?
Many thanks in advance.

**Comment by fairy-of-9** [comment]
Thank you for your comment.

`${data_dir}/*.jsonlines, ${data_dir}/*.v4_gold_conll` were made successfully.

I tried `GPU=0 python train.py train_1`
but, AssertionError occurred in evaluation.

It's my experiments.conf
```
data_dir = data

best {
  # Edit this
  data_dir = data
  model_type = independent
  # Computation limits.
  max_top_antecedents = 50
  max_training_sentences = 5
  top_span_ratio = 0.4
  max_num_speakers = 20
  max_segment_len = 256

  # Learning
  bert_learning_rate = 1e-5
  task_learning_rate = 2e-4
  num_docs = 2802

  # Model hyperparameters.
  dropout_rate = 0.3
  ffnn_size = 1000
  ffnn_depth = 1
  num_epochs = 20
  feature_size = 20
  max_span_width = 30
  use_metadata = true
  use_features = true
  use_segment_distance = true
  model_heads = true
  coref_depth = 2
  coarse_to_fine = true
  fine_grained = true
  use_prior = true

  # Other.
  train_path = train.english.jsonlines
  eval_path = dev.english.jsonlines
  conll_eval_path = dev.english.v4_gold_conll
  single_example = true
  genres = ["bc", "bn", "mz", "nw", "pt", "tc", "wb"]
  eval_frequency = 1000
  report_frequency = 100
  #log_root = ${data_dir}
  log_root = models
  adam_eps = 1e-6
  task_optimizer = adam
}

train_1 = ${best}{
  num_docs = 2802
  bert_learning_rate = 1e-05
  task_learning_rate = 0.0002
  max_segment_len = 128
  ffnn_size = 200
  model_heads = false
  train_path = ${data_dir}/train.english.128.jsonlines
  eval_path = ${data_dir}/dev.english.128.jsonlines
  conll_eval_path = ${data_dir}/dev.english.v4_gold_conll
  max_training_sentences = 5
  bert_config_file = data/cased_L-12_H-768_A-12/bert_config.json
  vocab_file = data/cased_L-12_H-768_A-12/vocab.txt
  tf_checkpoint = data/cased_L-12_H-768_A-12/bert_model.ckpt
  init_checkpoint = data/cased_L-12_H-768_A-12/bert_model.ckpt
}

```

and result
```
I0829 11:00:12.977631 139776037099264 train.py:58] [1000] loss=nan, steps/s=5.96
Loaded 343 eval examples.
2019-08-29 11:00:18.389048: W tensorflow/core/kernels/queue_base.cc:277] _0_padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "train.py", line 64, in <module>
    eval_summary, eval_f1 = model.evaluate(session, tf_global_step)
  File "/data/BERT-coref/coref/independent.py", line 559, in evaluate
    coref_predictions[example["doc_key"]] = self.evaluate_coref(top_span_starts, top_span_ends, predicted_antecedents, example["clusters"], coref_evaluator)
  File "/data/BERT-coref/coref/independent.py", line 524, in evaluate_coref
    predicted_clusters, mention_to_predicted = self.get_predicted_clusters(top_span_starts, top_span_ends, predicted_antecedents)
  File "/data/BERT-coref/coref/independent.py", line 499, in get_predicted_clusters
    assert i > predicted_index, (i, predicted_index)
AssertionError: (0, 0)

```

dev.english.128.jsonlines and dev.english.v4_gold_conll is

**Comment by mandarjoshi90** [comment]
I've added `cased_config_vocab/trial.jsonlines` as a full example. The README has been updated to include a brief explanation of keys. I'm closing this issue since the OP has opened a different one. Thanks!

**Comment by abhinandansrivastava** [comment]
Hey @fairy-of-9 @mandarjoshi90 @henlein ,

Can you please share a file for me to run one demo after that i will be able to make the format that this repo requires.
I am not able to find trial.jsonlines file in the cased_config_vocab folder.

Thanks in advance.

**Comment by mandarjoshi90** [comment]
Might be a better idea to look at the example in the README. I've also restored the trial.jsonlines file.

**Comment by abhinandansrivastava** [comment]
Hey @mandarjoshi90 ,
I tried making file in the format, still **predict.py** is still giving me error.
`ValueError: setting an array element with a sequence.`

i ran below code:
`python predict.py bert_base cased_config_vocab/TestingFile.jsonlines cased_config_vocab/15.jsonlines`


{"doc_key": "wb", "sentences": ["[CLS]", "who", "was", "jim", "henson", "?", "jim", "henson", "was", "a", "puppet", "##eer", ".", "[SEP]"], "speakers": ["[SPL]", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "[SPL]"], "clusters": [[]], "sentence_map": [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2], "subtoken_map": [0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 10, 10]}
{"doc_key": "wb", "sentences": ["[CLS]", "i", "am", "going", "to", "goa", "and", "love", "biology", ".", "[SEP]"], "speakers": ["[SPL]", "-", "-", "-", "-", "-", "-", "-", "-", "-", "[SPL]"], "clusters": [[]], "sentence_map": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], "subtoken_map": [0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 8]}
[TestingFile.zip](https://github.com/mandarjoshi90/coref/files/3858464/TestingFile.zip)
