### ISSUE TITLE
Has anyone got this to work?

### ISSUE THREAD

**Issue by ANGELLOPARR** [mandarjoshi90/coref#101]
I've been using a conda python 3.7 environment and trying to get this working for coreference resolution. Installing requirements did not fully work and I can't even run the setup script. It all seems so broken but there are no other resources for SpanBERT for coreference resolution.

Does anyone have a fool-proof way to get this up and running for coreference resolution? Venv with a certain Python version / certain OS?

I'm on an M1 mac.

**Comment by preethiseshadri518** [comment]
Have you tried the instructions in the notebook? I followed the instructions exactly and found them to be very helpful. It took me a few attempts, and nothing changed between the attempts, so perhaps that's happening for you? I used a conda python 3.7 as well. Note: I haven't done training, so I can't comment on that, but this should at least help with setup.

**Comment by LifeIsStrange** [comment]
Installing requirements give me this error with python 3.7

```
Collecting MarkupSafe==1.0
  Downloading MarkupSafe-1.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\steph\AppData\Local\Programs\Python\Python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\steph\\AppData\\Local\\Temp\\pip-in
stall-j0x_51t9\\MarkupSafe\\setup.py'"'"'; __file__='"'"'C:\\Users\\steph\\AppData\\Local\\Temp\\pip-install-j0x_51t9\\MarkupSafe\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', ope
n)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\steph\AppData\Local\Temp\pip-pip
-egg-info-_o316lmn'
         cwd: C:\Users\steph\AppData\Local\Temp\pip-install-j0x_51t9\MarkupSafe\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\steph\AppData\Local\Temp\pip-install-j0x_51t9\MarkupSafe\setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (C:\Users\steph\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```
@preethiseshadri518 @ANGELLOPARR 
How did you solve this guys?

**Comment by LifeIsStrange** [comment]
So I have applied the fixes from the google colab
sed 's/MarkupSafe==1.0/MarkupSafe==1.1.1/; s/scikit-learn==0.19.1/scikit-learn==0.21/; s/scipy==1.0.0/scipy==1.6.2/' < requirements.txt > tmp
! mv tmp requirements.txt


But there still remain an error and the colab no longer run.

```
Collecting psycopg2==2.7.4
  Using cached psycopg2-2.7.4.tar.gz (425 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\steph\AppData\Local\Programs\Python\Python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\steph\\AppData\\Local\\Temp\\pip-in
stall-lwpygzb4\\psycopg2\\setup.py'"'"'; __file__='"'"'C:\\Users\\steph\\AppData\\Local\\Temp\\pip-install-lwpygzb4\\psycopg2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(_
_file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\steph\AppData\Local\Temp\pip-pip-egg
-info-eqyrm3ps'
         cwd: C:\Users\steph\AppData\Local\Temp\pip-install-lwpygzb4\psycopg2\
    Complete output (23 lines):
    running egg_info
    creating C:\Users\steph\AppData\Local\Temp\pip-pip-egg-info-eqyrm3ps\psycopg2.egg-info
    writing C:\Users\steph\AppData\Local\Temp\pip-pip-egg-info-eqyrm3ps\psycopg2.egg-info\PKG-INFO
    writing dependency_links to C:\Users\steph\AppData\Local\Temp\pip-pip-egg-info-eqyrm3ps\psycopg2.egg-info\dependency_links.txt
    writing top-level names to C:\Users\steph\AppData\Local\Temp\pip-pip-egg-info-eqyrm3ps\psycopg2.egg-info\top_level.txt
    writing manifest file 'C:\Users\steph\AppData\Local\Temp\pip-pip-egg-info-eqyrm3ps\psycopg2.egg-info\SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).
```
Why is the mighty field of artificial intelligence in such an abandonware state..
