### ISSUE TITLE
Requirements txt is broken

### ISSUE THREAD

**Issue by LifeIsStrange** [mandarjoshi90/coref#116]
Python 3.7

```
Collecting MarkupSafe==1.0
  Downloading MarkupSafe-1.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\steph\AppData\Local\Programs\Python\Python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\steph\\AppData\\Local\\Temp\\pip-in
stall-j0x_51t9\\MarkupSafe\\setup.py'"'"'; __file__='"'"'C:\\Users\\steph\\AppData\\Local\\Temp\\pip-install-j0x_51t9\\MarkupSafe\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', ope
n)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\steph\AppData\Local\Temp\pip-pip
-egg-info-_o316lmn'
         cwd: C:\Users\steph\AppData\Local\Temp\pip-install-j0x_51t9\MarkupSafe\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\steph\AppData\Local\Temp\pip-install-j0x_51t9\MarkupSafe\setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (C:\Users\steph\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by evelinamorim** [comment]
Try to update your setuptools==45. I had a similar issue and it worked for me.
