### ISSUE TITLE
Path error when run bert_base and spanbert_base

### ISSUE THREAD

**Issue by jiezhongqiu** [mandarjoshi90/coref#14]
Hi, I tried to run `python train.py <experiment>` following the instruction in README. I tried `<experiment>=bert_base` and `<experiment>=spanbert_base`. and set `export data_dir=/data/coref`. I met the following errors:

* bert_base

```
Restoring from: /data/coref/bert_base/model-57000
W1010 16:06:31.544241 140159242708736 deprecation.py:323] From /home/jiezhong/anaconda3/envs/coref/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File "train.py", line 41, in <module>
    saver.restore(session, ckpt.model_checkpoint_path)
  File "/home/jiezhong/anaconda3/envs/coref/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1278, in restore
    compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: /data/coref/bert_base/model-57000
```

The bert_base directory created by `./download_pretrained.sh bert_base` contains:

```
bert_config.json  checkpoint  events.out.tfevents.1551148806.learnfair2008  events.out.tfevents.1551148825.learnfair0213  events.out.tfevents.1551148826.learnfair0213  model.max.ckpt.data-00000-of-00001  model.max.ckpt.index  stdout.log  vocab.txt
```

* spanbert_base

```
Restoring from: /checkpoint/danqi/coref_eval/final/base_pair_external_sl384_blr2e-05_tlr0.0001/model-57000
W1010 15:52:59.750342 139657016100608 deprecation.py:323] From /home/jiezhong/anaconda3/envs/coref/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File "train.py", line 41, in <module>
    saver.restore(session, ckpt.model_checkpoint_path)
  File "/home/jiezhong/anaconda3/envs/coref/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1276, in restore
    if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
  File "/home/jiezhong/anaconda3/envs/coref/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/jiezhong/anaconda3/envs/coref/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_management.py", line 372, in checkpoint_exists
    if file_io.get_matching_files(pathname):
  File "/home/jiezhong/anaconda3/envs/coref/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 363, in get_matching_files
    return get_matching_files_v2(filename)
  File "/home/jiezhong/anaconda3/envs/coref/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 384, in get_matching_files_v2
    compat.as_bytes(pattern))
tensorflow.python.framework.errors_impl.NotFoundError: /checkpoint/danqi/coref_eval/final/base_pair_external_sl384_blr2e-05_tlr0.0001; No such file or directory
```

It seems that the path `/checkpoint/danqi/coref_eval/final/base_pair_external_sl384_blr2e-05_tlr0.0001` is hard-coded somewhere. Moreover, the spanbert_base directory created by `./download_pretrained.sh spanbert_base` contains:

```
bert_config.json  checkpoint  events.out.tfevents.1561596094.learnfair1413  model.max.ckpt.data-00000-of-00001  model.max.ckpt.index  stdout.log  vocab.txt
```

Any help would be greatly appreciated!

**Comment by mandarjoshi90** [comment]
Could you please paste your experiments.conf?

**Comment by xptree** [comment]
@mandarjoshi90  I am using the origin `experiments.conf` in your repo (https://github.com/mandarjoshi90/coref/blob/master/experiments.conf)

**Comment by mandarjoshi90** [comment]
This is quite odd and I don't see why you'd run into this. I can't find the paths you mentioned anywhere. Do you happen to have an older commit/branch by any chance? If not, I'd suggest putting a breakpoint in `train.py` to see what config is being used.

**Comment by xptree** [comment]
@mandarjoshi90  Let me double check it.

**Comment by mandarjoshi90** [comment]
I'm closing this due to inactivity. Please feel free to reopen if you need to.

**Comment by nayakneha** [comment]
Hello,

I'm seeing this error too. The hardcoded paths are in `/spanbert/checkpoint` when downloaded from http://nlp.cs.washington.edu/pair2vec/spanbert_base.tar.gz:

```
[nnayak@node028 coref]$ cat ~/spanbert_data/spanbert_base/checkpoint
model_checkpoint_path: "/checkpoint/danqi/coref_eval/final/base_pair_external_sl384_blr2e-05_tlr0.0001/model-57000"
all_model_checkpoint_paths: "/checkpoint/danqi/coref_eval/final/base_pair_external_sl384_blr2e-05_tlr0.0001/model-53000"
all_model_checkpoint_paths: "/checkpoint/danqi/coref_eval/final/base_pair_external_sl384_blr2e-05_tlr0.0001/model-54000"
all_model_checkpoint_paths: "/checkpoint/danqi/coref_eval/final/base_pair_external_sl384_blr2e-05_tlr0.0001/model-55000"
all_model_checkpoint_paths: "/checkpoint/danqi/coref_eval/final/base_pair_external_sl384_blr2e-05_tlr0.0001/model-56000"
all_model_checkpoint_paths: "/checkpoint/danqi/coref_eval/final/base_pair_external_sl384_blr2e-05_tlr0.0001/model-57000"
```

This is the config printed out from train.py:
```
Config:
data_dir /sdb/data/new_coref
model_type independent
max_top_antecedents 50
max_training_sentences 3
top_span_ratio 0.4
max_num_speakers 20
max_segment_len 384
bert_learning_rate 2e-05
task_learning_rate 0.0001
num_docs 2802
dropout_rate 0.3
ffnn_size 3000
ffnn_depth 1
num_epochs 20
feature_size 20
max_span_width 30
use_metadata True
use_features True
use_segment_distance True
model_heads True
coref_depth 2
coarse_to_fine True
fine_grained True
use_prior True
train_path /home/nnayak/spanbert_data/train.english.384.jsonlines
eval_path /home/nnayak/spanbert_data/dev.english.384.jsonlines
conll_eval_path /home/nnayak/spanbert_data/dev.english.v4_gold_conll
single_example True
genres ['bc', 'bn', 'mz', 'nw', 'pt', 'tc', 'wb']
eval_frequency 1000
report_frequency 100
log_root /home/nnayak/spanbert_data
adam_eps 1e-06
task_optimizer adam
bert_config_file /home/nnayak/spanbert_data/spanbert_base/bert_config.json
vocab_file /home/nnayak/spanbert_data/spanbert_base/vocab.txt
tf_checkpoint /home/nnayak/spanbert_data/spanbert_base/model.max.ckpt
init_checkpoint /home/nnayak/spanbert_data/spanbert_base/model.max.ckpt
log_dir /home/nnayak/spanbert_data/spanbert_base
```

And here is the error:
```
Traceback (most recent call last):
  File "train.py", line 46, in <module>
    saver.restore(session, ckpt.model_checkpoint_path)
  File "/home/nnayak/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1276, in restore
    if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
  File "/home/nnayak/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/nnayak/.local/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_management.py", line 372, in checkpoint_exists
    if file_io.get_matching_files(pathname):
  File "/home/nnayak/.local/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 363, in get_matching_files
    return get_matching_files_v2(filename)
  File "/home/nnayak/.local/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 384, in get_matching_files_v2
    compat.as_bytes(pattern))
tensorflow.python.framework.errors_impl.NotFoundError: /checkpoint/danqi/coref_eval/final/base_pair_external_sl384_blr2e-05_tlr0.0001; No such file or directory
```
Please let me know how to proceed. We'd really like to be able to fine tune a span bert model.

Thank you!

**Comment by mandarjoshi90** [comment]
Neha, thanks so much for finding this. This happened because `train.py` tried to pickup the checkpoint already finetuned on coref. I should have clarified this in the instructions. I'm sorry. Please add this to your `experiments.conf`

```
train_spanbert_base = ${spanbert_base}{
tf_checkpoint = ${best.log_root}/cased_L-12_H-768_A-12/bert_model.ckpt
init_checkpoint = ${best.log_root}/spanbert_hf_base/pytorch_model.bin
}
```
where `${best.log_root}/spanbert_hf_base/pytorch_model.bin` points to the original SpanBERT (not finetuned) weight file which can be downloaded from here -- https://dl.fbaipublicfiles.com/fairseq/models/spanbert_hf_base.tar.gz

Note that you might still have to scale down `ffnn_size` if you have a 12GB GPU. I think 1000 works well but you might see a slight drop in performance.

**Comment by nayakneha** [comment]
Awesome, it seems to be training with those changes. I'll try the suggested changes in hyperparameters as well.

Thank you so much for the quick response!
