### ISSUE TITLE
undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

### ISSUE THREAD

**Issue by TatianaMoteuN** [mandarjoshi90/coref#62]
Hello
Please after setup all the requirements , I want now to do a setup for training by running this command `./setup_training.sh <ontonotes/path/ontonotes-release-5.0> $data_dir`
but i am getting this error 
"  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/envs/coref/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/envs/coref/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/envs/coref/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/envs/coref/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "minimize.py", line 14, in <module>
    import util
  File "/home/jupyter/coref/util.py", line 16, in <module>
    import independent
  File "/home/jupyter/coref/independent.py", line 14, in <module>
    import coref_ops
  File "/home/jupyter/coref/coref_ops.py", line 8, in <module>
    coref_op_library = tf.load_op_library("./coref_kernels.so")
  File "/opt/conda/envs/coref/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./coref_kernels.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs"

Please is there a way to fix this issue?

**Comment by grig-guz** [comment]
Looks like solution is here: #29
